name: CyberCat CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    name: Build and Validate Code
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET environment
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Adjust this version based on your project requirements

      # Step 3: Install dependencies and restore NuGet packages
      - name: Restore NuGet packages
        run: dotnet restore PROG6221_POE_ChatBot_ST10435066.sln

      # Step 4: Build the project
      - name: Build the solution
        run: dotnet build PROG6221_POE_ChatBot_ST10435066.sln --no-restore --configuration Release

      # Step 5: Run Code Formatter Check
      - name: Run Code Formatter Check
        run: dotnet format PROG6221_POE_ChatBot_ST10435066.sln --check

      # Step 6: Run Unit Tests (if applicable)
      - name: Run Unit Tests
        run: dotnet test PROG6221_POE_ChatBot_ST10435066.sln --no-build --verbosity normal
