name: CyberCat CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  build:
    name: Build and Validate Code
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET environment
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Adjust this version based on your project requirements

      # Step 3: Install dependencies and restore NuGet packages
      - name: Restore NuGet packages
        run: dotnet restore

      # Step 4: Build the project
      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      # Step 5: Run code analysis (optional but recommended for formatting checks)
      - name: Run Code Formatter Check
        run: dotnet format --check # Ensure code formatting standards are met

      # Step 6: Run tests (if applicable)
      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal
