name: .NET CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest # Use Windows as your project relies on SoundPlayer

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0 # Specify the .NET version you're using (adjust if different)

      # Step 3: Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Step 5: Run tests (Optional, if you have tests configured)
      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      # Step 6: Verify the WAV file exists
      - name: Verify WAV file exists
        shell: cmd
        run: |
          if not exist "Chatbot_voice_greeting.wav" (
            echo "Error: WAV file 'Chatbot_voice_greeting.wav' is missing."
            exit /b 1
          )
